export const RECEIVE_NEWS = 'RECEIVE_NEWS';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

export const RECEIVE_TRADE_HISTORY = 'RECEIVE_TRADE_HISTORY';

export const RECEIVE_MANAGE_STAFF = 'RECEIVE_MANAGE_STAFF';
export const ADD_STAFF = 'ADD_STAFF';
export const EDIT_STAFF = 'EDIT_STAFF';